name: Run Tests on PR

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest # You can change the OS as per your preference

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "8.0.6" # Replace with your desired .NET version

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build

      - name: Run Tests
        run: |
          cd afh-be.Tests
          dotnet test
